version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agendabarber_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  symfony:
    build: ./symfony
    container_name: symfony
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - mariadb
    expose:
      - '9000'
    command: php-fpm

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - symfony

  nextjs:
    build: ./nextjs
    container_name: nextjs
    working_dir: /app
    volumes:
      - ./nextjs:/app
    ports:
      - '3000:3000'
    command: ['waitSymfony.sh', 'npm', 'run', 'dev']
    depends_on:
      - nginx

volumes:
  db_data:
